# This file defines the Apple M1 chip settings. It overrides docker-compose.override.yml,
# which defines the development settings.
# To use it it is required to explicitly define if you want to build with it:
# > docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.apple-m1.override.yml up

services:
  ########################################################
  # FRONTEND #############################################
  ########################################################
  frontend:
    platform: linux/amd64

  ########################################################
  # ADMIN INTERFACE ######################################
  ########################################################
  admin:
    platform: linux/amd64

  #########################################################
  ## MARIADB ##############################################
  #########################################################
  mariadb:
    platform: linux/amd64
      
  ########################################################
  # BACKEND ##############################################
  ########################################################
  backend:
    platform: linux/amd64

  ########################################################
  # DATABASE #############################################
  ########################################################
  database:
    platform: linux/amd64
    
  #########################################################
  ## NGINX ################################################
  #########################################################
  nginx:
    platform: linux/amd64
